# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [12]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [13]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.01648346 0.02710512 0.37372853 ... 0.02650594 0.94790038 0.22627582]
 [0.11657214 0.69569376 0.48475815 ... 0.15085581 0.73410624 0.5433169 ]
 [0.43340021 0.35043021 0.60686738 ... 0.80276765 0.25318546 0.07222941]
 ...
 [0.7012893  0.49506067 0.83100211 ... 0.42906505 0.39290153 0.3555284 ]
 [0.52076997 0.27468924 0.92460212 ... 0.58517438 0.03801339 0.50280262]
 [0.48245842 0.2171645  0.89556806 ... 0.92343988 0.40216772 0.00533083]]
[[0.90573655 0.43790226 0.55513339 ... 0.3799225  0.29447094 0.38861553]
 [0.66404311 0.43869071 0.7543838  ... 0.04612273 0.52667394 0.25265764]
 [0.41844495 0.91121633 0.25230802 ... 0.49437842 0.10144514 0.52353254]
 ...
 [0.4230215  0.7502309  0.61373013 ... 0.9735175  0.03476933 0.52469379]
 [0.98461971 0.12307282 0.69991679 ... 0.84634736 0.16878935 0.54985532]
 [0.57672435 0.48285048 0.77004108 ... 0.2340861  0.47834827 0.6180662 ]]


Без использования numpy

In [9]:
def mult(a, b):
    result = [[0 for _ in range(len(a))] for _ in range(len(a))]
    for i in range(len(a)):
        for j in range(len(a)):
            for k in range(len(a)):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [10]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [14]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 453 ms, sys: 0 ns, total: 453 ms
Wall time: 456 ms


In [15]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.09 ms, sys: 19 µs, total: 1.11 ms
Wall time: 3.81 ms


In [16]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.518074554951454e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [17]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.10276808 0.52956524 0.33239705] [0.74657564 0.87328514 0.86535641]


In [18]:
def scalar_product(a, b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [22]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s

In [23]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 13 µs, sys: 2 µs, total: 15 µs
Wall time: 17.2 µs
CPU times: user 93 µs, sys: 0 ns, total: 93 µs
Wall time: 95.8 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** ________________________________

NumPy обеспечивает высокую эффективность благодаря векторизации. Операции выполняются на массивах данных, что позволяет использовать оптимизированные алгоритмы. Из-за этого скорость вычислений превосходит алтернативные решения.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [24]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    diagonal_elements = np.diag(a)
    even_diagonal_elements = diagonal_elements[diagonal_elements % 2 == 0]
    if len(even_diagonal_elements) == 0:
        return 0
    res = np.sum(even_diagonal_elements)
    return res

In [26]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[9, 3, 8, 3, 3],
       [3, 9, 8, 3, 3],
       [6, 5, 6, 5, 4],
       [7, 5, 6, 1, 4],
       [8, 7, 4, 9, 2]])

In [25]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 87 µs, sys: 16 µs, total: 103 µs
Wall time: 106 µs


0.0

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [27]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    X = np.array(A)
    cum_sums = np.cumsum(X, axis=1)
    result = cum_sums / np.arange(1, X.shape[1] + 1)
    return result

In [28]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.63021545 0.93175453 0.71539941 0.27929245 0.56468562 0.88308961
 0.02394258 0.59444768 0.18640638 0.40203534 0.25211652 0.00784309
 0.86627206 0.75691829 0.73782289 0.88161211 0.5270095  0.1908567
 0.41113249 0.88788306 0.05194316 0.61789681 0.6908828  0.38094201
 0.71113986 0.01335708 0.69259698 0.82499547 0.82008618 0.86006274
 0.26464919 0.13470668 0.64544767 0.60031292 0.76464946 0.26156634
 0.07640325 0.26049756 0.36042236 0.21870611 0.84158668 0.03897475
 0.20182104 0.71333307 0.55074824 0.76973172 0.564039   0.06906874
 0.76754762 0.79383319 0.41498797 0.33496894 0.68362916 0.5266539
 0.85118979 0.50973393 0.74432635 0.18851196 0.11941832 0.24820404
 0.44095861 0.48784167 0.68493842 0.3230004  0.07030608 0.3654021
 0.60017308 0.50956536 0.16736009 0.74836026 0.66560047 0.86062428
 0.32575508 0.75891294 0.57564202 0.91391331 0.07351873 0.53486932
 0.72485734 0.32082278 0.54236681 0.03004405 0.61702276 0.92886033
 0.36688089 0.86848797 0.2919381  0.24946019 0.47050612 0.5484678

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [29]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    elements = []
    counts = []
    if len(a) == 0:
        return np.array([]), np.array([])
    current_element = a[0]
    current_count = 1
    for i in range(1, len(a)):
        if a[i] == current_element:
            current_count += 1
        else:
            elements.append(current_element)
            counts.append(current_count)
            current_element = a[i]
            current_count = 1
    elements.append(current_element)
    counts.append(current_count)
    elements_array = np.array(elements)
    counts_array = np.array(counts)

    return elements_array, counts_array

In [30]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 20 µs, sys: 3 µs, total: 23 µs
Wall time: 26.9 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [31]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    X_copy = np.copy(X)
    X_copy[1::2] = a
    X_copy[::2] = X_copy[::2] ** 3
    reversed_X = X_copy[::-1]
    result = np.concatenate((X, reversed_X))

    return result

In [32]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 118 µs, sys: 0 ns, total: 118 µs
Wall time: 170 µs
